### ISSUE TITLE
Initial Project Implemention

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#1]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

**Main Idea:**
Create a library that provides the ability to pull various information about github using the GitHub API.  This kind of code is being used in the [GithubReleaseChecker](https://github.com/KinsonDigital/GithubReleaseChecker) GItHub action.   Take the `GitHubDataService` code as a start for the library.  

**HTTP Headers:**
Add the ability to add headers to the requests in the `IHttpRequest` and `HttpRequest` types.  This will eventually be required for other actions.

Make sure to keep the API simple without requiring any more dependencies on dotnet or other libraries.
One idea is to use a `KeyValuePair<string, string>` type for the headers.  This was done in the past for a company and it worked out pretty well when creating an HTTP client abstraction.

Make sure that all of the required models are also migrated over to this project.

### Acceptance Criteria

**This issue is finished when:**
- [x] Project created with the name **GitHubData**
- [x] Repo branch settings setup
- [x] Project repo setup for contributions and `FUNDING.yml` added to project
- [x] Create thin wrapper around RestSharp client to make testing and mocking easier
  - [x] Add RestSharp nuget package to project.
- [x] Models migrated to this project.
- [x] Ability to add HTTP headers
- [x] Ability to change a header value that already exists
- [x] Create workflows
  - [x] Create build status check workflow
  - [x] Create unit testing status check workflow
  - [x] Create release workflow to release packages for preview
  - [x] ~~Create release workflow to release packages for production~~
- [x] Create templates
  - [x] Add Bug Issue template
  - [x] Add Project issue template
- [x] Create issue to add this new library to [VersionMiner](https://github.com/KinsonDigital/VersionMiner)
  - This issue will explain that it needs to remove the old code and implement/use the new code.
- [x] Unit tests added
- [x] Create README file
  - [x] Add badges to README
  - [x] Setup README similar to the Velaptor README but refactor to fit this project context
- [x] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Related Work

- KinsonDigital/GitHubReleaseChecker#2
- #8
- KinsonDigital/VersionMiner#48

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    |  https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes     |
| Enhancement         | https://github.com/KinsonDigital/GitHubData/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.****

**Comment by CalvinWilkinson** [comment]
Did not implement production workflow.  This has been converted into a new issue for the future.
