### ISSUE TITLE
🚧Various improvements

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#33]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Make various improvements listed in the **Acceptance Criteria**.

### Acceptance Criteria

- [x] Add new `GetAsync()` method to the `HTTPClient` class and `IHTTPClient` interface https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature
- [x] Add new service that can be used to get GitHub API rate limit information and use it in `GitHubDataService` class https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature
- [x] Add code to catch rate limit and show custom exception.  https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature
  - This is HTTP status code Forbidden (403)
  - Make sure to pass the rate limit exception message out of the method to be viewed
- [x] Add `ClearHeaders()` method to `HTTPClient` class and associated interface https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature
  - You can clear and add headers using the Parameters methods
- [x] Add `RemoveHeader()` method to the `HTTPClient` class and associated interface https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature
- [x] Create service factory to create all of the project services https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature
  - This is for users who cannot or do not want to use dependency injection.
- [x] ~~Remove the internal `nextRequestHeaders` collection in the HTTPClient class~~ 
  - ~~This is not needed after adding the `ClearHeaders()` method~~
- [x] Add content types to proper requests in the `GitHubDataService` https://github.com/KinsonDigital/GitHubData/labels/tech%20debt
  - Accept header with a value of `application/vnd.github.v3+json` for everything but the `GetFileDataAsync()` method
- [x] ~~In the integration tests, add try catch around async await calls that are **NOT** supposed to throw exceptions 🪧~~
  - ~~This way we can see any exceptions when executing integration tests.~~
- [x] Add method to `GitHubDataService` class that allows the adding of the auth token to auth the requests https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature
  - ~Make sure to use the `SecureString` type.  You can look up how to pull the string out before the request~
  - Also clear and re-add the auth token header before and after the request is made.  This way the secure string value does not hang around.
- [x] Move service classes to Services folder and adjust namespaces. https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes

### ToDo Items

- [x] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [x] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [x] Issue linked to the correct project _(if required)_.
- [x] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Related Work

- KinsonDigital/VersionMiner#38

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
It has been discovered that removing the class field `nextRequestHeaders` is not going to work to accomplish the work required for this issue.  It will be kept and utilized.

**Comment by CalvinWilkinson** [comment]
I did not implement any of the changes required to check for non exception throwing in the integration tests.
This work was already done.
