### ISSUE TITLE
🚧Add ability to add headers to requests

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#4]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add the ability to add headers to the requests in the `IHttpRequest` and `HttpRequest` types.  This will eventually be required for other actions.

Make sure to keep the API simple without requiring any more dependencies on dotnet or other libraries.
One idea is to use a `KeyValuePair<string, string>` type for the headers.  This was done in the past for a company and it worked out pretty well when creating an HTTP client abstraction.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Ability to add HTTP headers
- [ ] Ability to remove HTTP headers
- [ ] Ability to change a header value that already exists
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Related Work

- KinsonDigital/VersionMiner#49

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/GitHubData/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Transferred this issue to the main implementation issue below.  Decided to release this in **preview.1** instead of in a future release due to needing other actions needing this functionality as soon as possible.

- #1
