### ISSUE TITLE
🚧Collect request limit data

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#44]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add a feature to the `GithubDataService` to collect the **GitHub API** request limit data on every request.
Add a readonly data property of type `RateLimit` to the `GitHubDataService`.  Every time a request is made, this will be updated.

This data is located in the response headers below for each request.  This can be retrieved from the `RestResponse.Headers` when **RestSharp** completes a request.  Make sure to check that the headers exists first.  If the headers to not exist, then do not update the property data.

**The header names are below:**
- X-RateLimit-Limit
- X-RateLimit-Remaining
- X-RateLimit-Used

Add an extra property to the `RateLimit` class to hold a bool value representing if the LAST request made as an authorized request.

### Acceptance Criteria

- [ ] Readonly `RateLimit` property added to the `GitHubDataService` class
- [ ] Readonly `RateLimit` property added to the `IGitHubDataService` interface
- [ ] Property named `AuthorizedRequest` of type bool added to the `RateLimit` class
- [ ] All methods of the `GitHubDataService` class updated to update the `RateLimit` property
- [ ] Create an issue for the **VersionMiner** project to update to the newest **GitHubdata** version and to add a feature to print the request limits to the console.
  - The rate limits will be collected and printed just after the last request made to the **GitHub API**.

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes.

**Reason:** Project deprecated
