### ISSUE TITLE
🚧Setup release workflows

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#46]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Update the `preview-release.yml` release workflow and create a `production-release.yml` workflow.

Currently the existing `preview-release.yml` workflow has a job commented out that uses the **VersionMiner** GitHub action.   Uncomment this job and update the **VersionMiner** action to use ~**v1.0.0-preview.3**~ **v1.0.0-preview.2**.

### Acceptance Criteria

- [x] Preview release workflow
  - [x] `get_version_from_project_file` job enabled
  - [x] **VersionMiner** action updated to **v1.0.0-preview.2**
  - [x] `publish_nuget_package` job enabled and setup to consume `get_version_from_project_file` output
- [x] Production release workflow created
- [x] Main branch for repo set back to latest preview

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [x] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
