### ISSUE TITLE
🚧Error not correctly being logged to github console

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#50]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

When an error occurs while running the GitHub action in GitHub, the GitHub console output is not rendering an error correctly.

**Example Of Issue (Refer to line 31): **
<img width="622" alt="image" src="https://user-images.githubusercontent.com/85414302/186032200-3bc20999-e12c-4549-a0ee-d7f2d3a3cc98.png">

Refer to [this Preview Release](https://github.com/KinsonDigital/GitHubData/runs/7962499156?check_suite_focus=true) for the actual console issue.

This is most likely due to the fact that the workflow command `::error::` (which is GitHub syntax), is not on its own line.  For it to render correctly as an error, the error must be on its own line.

🧪NOTE ABOUT TESTING🧪
This is going to have to be tested manually by purposely throwing an error. This can be done by passing an incorrect file path in the workflow.  Make sure that the NuGet package job is temporarily disabled before running the test.  Also temporarily switch the main repo branch to the branch of this issue's PR so the workflow can be executed for testing. 

### Acceptance Criteria

- [ ] GitHub console errors renders correctly in the GitHub console
- [ ] Disabled NuGet job in workflow re-enabled
- [ ] Main repo branch reset back to proper branch

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [X] Issue linked to the correct milestone _(if required)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes.

**Reason:** Project deprecated
