### ISSUE TITLE
🚧Setup release workflows to do GitHub releases

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#51]
### Complete The Item Below

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Setup both the `preview-release.yml` and `production-release.yml` release workflows to perform a GitHub release.   This release will check if the release notes exist, contain a certain title, add the release notes to the release description, and attach the release notes to the release assets.

💡Temporarily change the repo's default branch for testing.

### Acceptance Criteria

- ### **Preview release workflow updated**
   - [ ] Checks if the release notes exist
   - [ ] Title constructed with the version and to look like 👉🏼 **🚀Preview Release - v1.2.3-preview.4**
   - [ ] Checks if release notes exist and if not, fails the workflow
   - [ ] Adds the release notes to the description of the release
   - [ ] Attaches the release notes to the assets of the release

- ### **Production release workflow updated**
   - [ ] Checks if the release notes exist
   - [ ] Title constructed with the version and to look like 👉🏼 **🚀Preview Release - v1.2.3**
   - [ ] Checks if release notes exist and if not, fails the workflow
   - [ ] Adds the release notes to the description of the release
   - [ ] Attaches the release notes to the assets of the release

- [ ] The repo's default branch changed back to latest preview

### ToDo Items

- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Issue linked to the correct project _(if required)_.
- [x] Issue linked to the correct milestone _(if required)_.
- [ ] Draft pull request created and linked to this issue _(only required with code changes)_.

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature         | https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature              |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without PR or changes.

**Reason:** This issue was a duplicate and completed by the issue below:
- #46
