### ISSUE TITLE
🚧Implement SWCM and integration tests

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#6]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Implement/use the new SWCM tool into the projects integration tests to help simplify authentication when the integration tests make HTTP requests.  This is to help prevent a max out on the number of HTTP requests when not authenticating the request.

### Acceptance Criteria

**This issue is finished when:**
- [ ] Unit tests added
- [ ] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [ ] Draft pull request created and linked to this issue.

### Issue Dependencies

- KinsonDigital/SWCM#1

### Related Work

- #8

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| Enhancement         | https://github.com/KinsonDigital/GitHubData/labels/enhancement                         |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.

**Comment by CalvinWilkinson** [comment]
Closed without changes.

**Reason:** Project deprecated
