### ISSUE TITLE
🚧Add checks for branch exists and downloading file data

### ISSUE THREAD

**Issue by CalvinWilkinson** [KinsonDigital/GitHubData#7]
### I have done the items below . . .

- [X] I have updated the title without removing the 🚧 emoji.

### Description

Add more capability to the `IGitHubDataService` and `GitHubDataService` types to be able to check if a GIT branch exists and also the ability to download file data from the repository.

### Acceptance Criteria

**This issue is finished when:**
- [x] Ability to check if a GIT branch exists
- [x] Ability to download file data
- [x] Unit tests added
- [x] All unit tests pass

### ToDo Items

- [X] Priority label added to this issue.  Refer to the _**Priority Type Labels**_ section below.
- [X] Change type labels added to this issue.  Refer to the _**Change Type Labels**_ section below.
- [X] Issue linked to the correct project.
- [X] Issue linked to the correct milestone.
- [x] Draft pull request created and linked to this issue.

### Related Work

- #8
- KinsonDigital/VersionMiner#48

### Additional Information:

**_<details closed><summary>Change Type Labels</summary>_**

| Change Type         | Label                                                                                |
|---------------------|--------------------------------------------------------------------------------------|
| Bug Fixes           | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%90%9Bbug                     |
| Breaking Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%A7%A8breaking%20changes      |
| New Feature | https://github.com/KinsonDigital/GitHubData/labels/%E2%9C%A8new%20feature                         |
| Workflow Changes    | https://github.com/KinsonDigital/GitHubData/labels/workflow                            |
| Code Doc Changes    | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%91documentation%2Fcode    |
| Product Doc Changes | https://github.com/KinsonDigital/GitHubData/labels/%F0%9F%93%9Ddocumentation%2Fproduct |
</details>

**_<details closed><summary>Priority Type Labels</summary>_**

| Priority Type       | Label                                                              |
|---------------------|--------------------------------------------------------------------|
| Low Priority        | https://github.com/KinsonDigital/GitHubData/labels/low%20priority    |
| Medium Priority     | https://github.com/KinsonDigital/GitHubData/labels/medium%20priority |
| High Priority       | https://github.com/KinsonDigital/GitHubData/labels/high%20priority   |
</details>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct.
